const types = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_FINISHED: 'LOGIN_FINISHED',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_FINISHED: 'LOGOUT_FINISHED',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  FETCH_POSTS_START: 'FETCH_POSTS_START',
  FETCH_POSTS_FINISHED: 'FETCH_POSTS_FINISHED',
  FETCH_POSTS_ERROR: 'FETCH_POSTS_ERROR',
  ADD_POST_START: 'ADD_POST_START',
  ADD_POST_FINISHED: 'ADD_POST_FINISHED',
  ADD_POST_ERROR: 'ADD_POST_ERROR',
};

export default types;
