const types = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_FINISHED: 'LOGIN_FINISHED',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGOUT_START: 'LOGOUT_START',
  LOGOUT_FINISHED: 'LOGOUT_FINISHED',
  LOGOUT_ERROR: 'LOGOUT_ERROR',
  FETCH_DATA_START: 'FETCH_DATA_START',
  FETCH_DATA_FINISHED: 'FETCH_DATA_FINISHED',
  FETCH_DATA_ERROR: 'FETCH_DATA_ERROR',
  ADD_DATA_START: 'ADD_DATA_START',
  ADD_DATA_FINISHED: 'ADD_DATA_FINISHED',
  ADD_DATA_ERROR: 'ADD_DATA_ERROR'
};

export default types;
