# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'fakestagram' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fakestagram
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'BatchedBridge', # Required For React Native 0.45.0+
    'Core',
    'DevSupport'
    # Add any other subspecs you want to use in your project
  ]

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'

  target 'fakestagramTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'fakestagram-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for fakestagram-tvOS

  target 'fakestagram-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
